# SITE CONFIGURATION
title: Dev_Time # your site title
author: Dev-Time1025 # You :P
description: 이 사이트는 개발자 Dev_Time의 어플 소개 사이트입니다.# Meta description of Homepage
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://Dev-Time1025.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sungmo Ham
  links:
    - https://github.com/Dev-Time1025

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Apps', link: '/apps'}
  - {name: 'Privacy Policy', link: '/privacy_policy'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

# 타이틀 이미지 변경해야함
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: devtime1025@gmail.com # email for form submission

github_username:  Dev-Time1025# replace with your_github_username or comment to remove link from footer

disqus:
  shortname: dev_time# to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
