# SITE CONFIGURATION
title: Dev_Time
author: Dev-Time1025
description: >
 이 사이트는 개발자 Dev_Time의 어플 소개 사이트입니다.
baseurl: "/"
url: "https://Dev-Time1025.github.io/"

# SEO PLUGIN
social:
  name: Sungmo Ham
  links:
    - https://github.com/Dev-Time1025

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Apps', link: '/apps'}
  - {name: 'Privacy Policy', link: '/privacy_policy'}

tagline: >
  Welcome! Dev_Time's Portfolio!

# 타이틀 이미지 변경해야함
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: devtime1025@gmail.com

github_username:  Dev-Time1025

disqus:
  shortname: dev_time

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
